'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class MailMessages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.MailMessages", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;strong&gt;Cordial saludo&lt;/strong&gt;.&lt;br&gt;&lt;br&gt;&lt;p&gt;Apreciado @@UserName@@:&lt;br&gt;&lt;br&gt;
        '''La activación de su cuenta en el sistema de gestión docente del Campus Virtual UDES ha sido activada con éxito.&lt;br&gt;&lt;br&gt;
        '''Para continuar con su proceso de inscripción, siga las instrucciones que se indican a continuación.&lt;br&gt;&lt;br&gt;
        '''&lt;br&gt;&lt;br&gt;&lt;strong&gt;COMPLETAR INFORMACIÓN&lt;/strong&gt;&lt;br&gt;&lt;br&gt;
        '''1. Copie la siguiente dirección web: 
        ''' &lt;a href=&apos;@@urlWebAppr@@&apos;&gt;@@urlWebApp@@&lt;/a&gt;&lt;br&gt;
        '''IMPORTANTE: como el correo electrónico fraudulento (de suplant [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Email_ActivationRequest() As String
            Get
                Return ResourceManager.GetString("Email_ActivationRequest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;strong&gt;Cordial saludo&lt;/strong&gt;.&lt;br&gt;&lt;br&gt;&lt;p&gt;Apreciado @@UserName@@:&lt;br&gt;&lt;br&gt;
        '''Usted ha iniciado su proceso de inscripción en el sistema de gestión de docencia del Campus Virtual UDES.&lt;br&gt;&lt;br&gt;
        '''Para continuar con su proceso de inscripción necesitamos verificar la dirección de correo electrónico que nos fue suministrada en el momento de inscribirse en nuestro portal.&lt;br&gt;&lt;br&gt; 
        '''Para realizar esta verificación, siga las instrucciones que se indican a continuación.&lt;br&gt;&lt;br&gt;
        '''&lt;br&gt;&lt;br&gt;&lt;strong&gt;CONFIRMAR CORREO ELECTRO [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Email_VerificationRequest() As String
            Get
                Return ResourceManager.GetString("Email_VerificationRequest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verificación de correo electrónico.
        '''</summary>
        Friend Shared ReadOnly Property Email_VerificationRequestTitle() As String
            Get
                Return ResourceManager.GetString("Email_VerificationRequestTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hola @@EMAIL@@&lt;br /&gt;&lt;br /&gt;Hemos recibido su solicitud para restablecer su contraseña. Para confirmar la solicitud y restablecer su contraseña, siga las instrucciones que se indican a continuación.&lt;br /&gt;&lt;br /&gt;CONFIRMAR SOLICITUD Y RESTABLECER CONTRASEÑA&lt;br /&gt;&lt;br /&gt;1. Copie la siguiente dirección web:&lt;br /&gt;&lt;br /&gt;&lt;a href=&quot;@@URL@@&quot;&gt;@@URL@@&lt;/a&gt;&lt;br /&gt;&lt;br /&gt;IMPORTANTE: como el correo electrónico fraudulento (de suplantación de identidad o &quot;phishing&quot;) utiliza a menudo vínculos falsos, se recomienda que no haga clic [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property PasswordReset_EmailRequest() As String
            Get
                Return ResourceManager.GetString("PasswordReset_EmailRequest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Información de recuperación de contraseña.
        '''</summary>
        Friend Shared ReadOnly Property PasswordReset_EmailRequestTitle() As String
            Get
                Return ResourceManager.GetString("PasswordReset_EmailRequestTitle", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
