'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Messages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.Messages", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cerrar esta ventana..
        '''</summary>
        Friend Shared ReadOnly Property ActionCloseWindow() As String
            Get
                Return ResourceManager.GetString("ActionCloseWindow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Volver adonde me encontraba trabajando..
        '''</summary>
        Friend Shared ReadOnly Property ActionContinue() As String
            Get
                Return ResourceManager.GetString("ActionContinue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Crear un registro nuevo..
        '''</summary>
        Friend Shared ReadOnly Property ActionCreate() As String
            Get
                Return ResourceManager.GetString("ActionCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Volver a la vista de los registros..
        '''</summary>
        Friend Shared ReadOnly Property ActionDefault() As String
            Get
                Return ResourceManager.GetString("ActionDefault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ir al inicio..
        '''</summary>
        Friend Shared ReadOnly Property ActionHome() As String
            Get
                Return ResourceManager.GetString("ActionHome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ha ocurrido un error al ejecutar la operación..
        '''</summary>
        Friend Shared ReadOnly Property ActionMessageError() As String
            Get
                Return ResourceManager.GetString("ActionMessageError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Operación completada satisfactoriamente..
        '''</summary>
        Friend Shared ReadOnly Property ActionMessageOk() As String
            Get
                Return ResourceManager.GetString("ActionMessageOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resultado de la operación:.
        '''</summary>
        Friend Shared ReadOnly Property ActionTitle() As String
            Get
                Return ResourceManager.GetString("ActionTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Intentar nuevamente..
        '''</summary>
        Friend Shared ReadOnly Property ActionTryAgain() As String
            Get
                Return ResourceManager.GetString("ActionTryAgain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ir a la URL....
        '''</summary>
        Friend Shared ReadOnly Property ActionUserDefined() As String
            Get
                Return ResourceManager.GetString("ActionUserDefined", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ver información detallada del registro..
        '''</summary>
        Friend Shared ReadOnly Property ActionView() As String
            Get
                Return ResourceManager.GetString("ActionView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No tiene permisos para acceder esta página..
        '''</summary>
        Friend Shared ReadOnly Property ApplicationAccessNotAllowed() As String
            Get
                Return ResourceManager.GetString("ApplicationAccessNotAllowed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usted no tiene los permisos suficientes para acceder esta página..
        '''</summary>
        Friend Shared ReadOnly Property ApplicationError403() As String
            Get
                Return ResourceManager.GetString("ApplicationError403", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La página que ha solicitado no se ha podido encontrar..
        '''</summary>
        Friend Shared ReadOnly Property ApplicationError404() As String
            Get
                Return ResourceManager.GetString("ApplicationError404", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El tiempo de espera de la solicitud a finalizado..
        '''</summary>
        Friend Shared ReadOnly Property ApplicationError408() As String
            Get
                Return ResourceManager.GetString("ApplicationError408", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El servidor no puede completar su solicitud en este momento..
        '''</summary>
        Friend Shared ReadOnly Property ApplicationError500() As String
            Get
                Return ResourceManager.GetString("ApplicationError500", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El servidor esta experimentando un alto tráfico de información..
        '''</summary>
        Friend Shared ReadOnly Property ApplicationError503() As String
            Get
                Return ResourceManager.GetString("ApplicationError503", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Por favor contacte al administrador del sistema..
        '''</summary>
        Friend Shared ReadOnly Property ApplicationErrorContact() As String
            Get
                Return ResourceManager.GetString("ApplicationErrorContact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Se ha generado un error en la aplicación, el cual ha sido registrado detalladamente. Una notificación al respecto ha sido enviada al administrador del sistema para realizar el seguimiento pertinente y tomar acciones correctivas de ser necesario. Lamentamos los inconvenientes que se hayan podido presentar..
        '''</summary>
        Friend Shared ReadOnly Property ApplicationErrorDescription() As String
            Get
                Return ResourceManager.GetString("ApplicationErrorDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ha ocurrido un error inesperado..
        '''</summary>
        Friend Shared ReadOnly Property ApplicationErrorUnexpected() As String
            Get
                Return ResourceManager.GetString("ApplicationErrorUnexpected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ha ocurrido un error en el servidor..
        '''</summary>
        Friend Shared ReadOnly Property ApplicationErrorUnknown() As String
            Get
                Return ResourceManager.GetString("ApplicationErrorUnknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La cuenta de usuario ya ha sido creada..
        '''</summary>
        Friend Shared ReadOnly Property AppUserAccountExits() As String
            Get
                Return ResourceManager.GetString("AppUserAccountExits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La cuenta de usuario no ha sido creada..
        '''</summary>
        Friend Shared ReadOnly Property AppUserAccountPending() As String
            Get
                Return ResourceManager.GetString("AppUserAccountPending", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La cuenta de correo electrónico no ha sido verificada..
        '''</summary>
        Friend Shared ReadOnly Property AppUserEmailPending() As String
            Get
                Return ResourceManager.GetString("AppUserEmailPending", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La cuenta de correo electrónico ha sido verificada correctamente..
        '''</summary>
        Friend Shared ReadOnly Property AppUserEmailVerified() As String
            Get
                Return ResourceManager.GetString("AppUserEmailVerified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ver información.
        '''</summary>
        Friend Shared ReadOnly Property ClickHereToView() As String
            Get
                Return ResourceManager.GetString("ClickHereToView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Al realizar esta operación no se podran adicionar mas vehiculos para este proceso de creación de T.O por Lotes.\n\n Desea Continuar ?.
        '''</summary>
        Friend Shared ReadOnly Property ClosedConfirmMessage() As String
            Get
                Return ResourceManager.GetString("ClosedConfirmMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El registro ha sido modificado por fuera de este formulario, posiblemente por otro usuario..
        '''</summary>
        Friend Shared ReadOnly Property ConfirmMessage() As String
            Get
                Return ResourceManager.GetString("ConfirmMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No hacer los cambios y permitir verificar la información.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmMessageDoNothing() As String
            Get
                Return ResourceManager.GetString("ConfirmMessageDoNothing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cargar de nuevo la información del registro.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmMessageReload() As String
            Get
                Return ResourceManager.GetString("ConfirmMessageReload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Al realizar esta operación todos los demás elementos relacionados con este registro podrían ser eliminados automáticamente.\n\nEstá seguro que desea borrar este registro?.
        '''</summary>
        Friend Shared ReadOnly Property DeleteConfirmMessage() As String
            Get
                Return ResourceManager.GetString("DeleteConfirmMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El correo electrónico ya existe..
        '''</summary>
        Friend Shared ReadOnly Property EmailNotAllowed() As String
            Get
                Return ResourceManager.GetString("EmailNotAllowed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Se ha aplicado una opción de filtrado no disponible en las opciones predeterminadas de filtrado del formulario..
        '''</summary>
        Friend Shared ReadOnly Property FilterOptionExternal() As String
            Get
                Return ResourceManager.GetString("FilterOptionExternal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se pudo verificar esta información correctamente. Inténtelo nuevamente..
        '''</summary>
        Friend Shared ReadOnly Property InvalidInformation() As String
            Get
                Return ResourceManager.GetString("InvalidInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Se esperaba el parámetro [ UNKNOWN ]..
        '''</summary>
        Friend Shared ReadOnly Property InvalidParamsParamExpected() As String
            Get
                Return ResourceManager.GetString("InvalidParamsParamExpected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Registro no encontrado..
        '''</summary>
        Friend Shared ReadOnly Property InvalidParamsRecordNotFound() As String
            Get
                Return ResourceManager.GetString("InvalidParamsRecordNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error no definido!!!!!.
        '''</summary>
        Friend Shared ReadOnly Property InvalidParamsUnknownError() As String
            Get
                Return ResourceManager.GetString("InvalidParamsUnknownError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La contraseña ha sido cambiada satisfactoriamente..
        '''</summary>
        Friend Shared ReadOnly Property PasswordChanged() As String
            Get
                Return ResourceManager.GetString("PasswordChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contraseña incorrecta..
        '''</summary>
        Friend Shared ReadOnly Property PasswordInvalid() As String
            Get
                Return ResourceManager.GetString("PasswordInvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Las contraseñas nuevas no coinciden..
        '''</summary>
        Friend Shared ReadOnly Property PasswordMismatch() As String
            Get
                Return ResourceManager.GetString("PasswordMismatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Se ha enviado al correo electrónico información de recuperación de contraseña..
        '''</summary>
        Friend Shared ReadOnly Property PasswordResetMailSent() As String
            Get
                Return ResourceManager.GetString("PasswordResetMailSent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No hay información relacionada para este elemento..
        '''</summary>
        Friend Shared ReadOnly Property RelatedInformationNotAvailable() As String
            Get
                Return ResourceManager.GetString("RelatedInformationNotAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inscripción Guardada Exitosamente !.
        '''</summary>
        Friend Shared ReadOnly Property SaveConfirmMessage() As String
            Get
                Return ResourceManager.GetString("SaveConfirmMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to En este momento estamos trabajando en esta aplicación. Discúlpenos por el inconveniente..
        '''</summary>
        Friend Shared ReadOnly Property SignInAppNotAvailable() As String
            Get
                Return ResourceManager.GetString("SignInAppNotAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se encontró la aplicación. Por favor contacte al administrador..
        '''</summary>
        Friend Shared ReadOnly Property SignInAppNotFound() As String
            Get
                Return ResourceManager.GetString("SignInAppNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Por favor verifique su información e inténtelo nuevamente..
        '''</summary>
        Friend Shared ReadOnly Property SignInErrorValidating() As String
            Get
                Return ResourceManager.GetString("SignInErrorValidating", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ha ocurrido un error inesperado. Por favor contacte al administrador..
        '''</summary>
        Friend Shared ReadOnly Property SignInUnknownError() As String
            Get
                Return ResourceManager.GetString("SignInUnknownError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ha finalizado su sesión..
        '''</summary>
        Friend Shared ReadOnly Property SignOutConfirm() As String
            Get
                Return ResourceManager.GetString("SignOutConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El nombre de usuario está disponible..
        '''</summary>
        Friend Shared ReadOnly Property UserNameAvailable() As String
            Get
                Return ResourceManager.GetString("UserNameAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El nombre de usuario no está disponible..
        '''</summary>
        Friend Shared ReadOnly Property UserNameNotAvailable() As String
            Get
                Return ResourceManager.GetString("UserNameNotAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Es necesario el nombre de usuario para realizar la verificación..
        '''</summary>
        Friend Shared ReadOnly Property UserNameRequired() As String
            Get
                Return ResourceManager.GetString("UserNameRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La información fue verificada correctamente..
        '''</summary>
        Friend Shared ReadOnly Property ValidInformation() As String
            Get
                Return ResourceManager.GetString("ValidInformation", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
