'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class AppResources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.AppResources", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Campus Virtual UDES - Acciones.
        '''</summary>
        Friend Shared ReadOnly Property ActionWindowTitle() As String
            Get
                Return ResourceManager.GetString("ActionWindowTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Campus Virtual UDES - Sistema de Administración CV-UDES.
        '''</summary>
        Friend Shared ReadOnly Property ApplicationName() As String
            Get
                Return ResourceManager.GetString("ApplicationName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sistema de Administración Docente CV-UDES.
        '''</summary>
        Friend Shared ReadOnly Property ApplicationTitle() As String
            Get
                Return ResourceManager.GetString("ApplicationTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /_Resources/Logos/AppLogo_ES.gif.
        '''</summary>
        Friend Shared ReadOnly Property AppLogo() As String
            Get
                Return ResourceManager.GetString("AppLogo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Desarrollado por Campus Virtual UDES.
        '''</summary>
        Friend Shared ReadOnly Property FooterLink() As String
            Get
                Return ResourceManager.GetString("FooterLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to © 2012 Campus Virtual UDES. Todos los derechos reservados..
        '''</summary>
        Friend Shared ReadOnly Property FooterText() As String
            Get
                Return ResourceManager.GetString("FooterText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Programas.
        '''</summary>
        Friend Shared ReadOnly Property HeaderAcademicPrograms() As String
            Get
                Return ResourceManager.GetString("HeaderAcademicPrograms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Registro &amp; Control.
        '''</summary>
        Friend Shared ReadOnly Property HeaderCoordinator() As String
            Get
                Return ResourceManager.GetString("HeaderCoordinator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mercadeo.
        '''</summary>
        Friend Shared ReadOnly Property HeaderMarketing() As String
            Get
                Return ResourceManager.GetString("HeaderMarketing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Matrículas.
        '''</summary>
        Friend Shared ReadOnly Property HeaderRegistrations() As String
            Get
                Return ResourceManager.GetString("HeaderRegistrations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recursos Aula.
        '''</summary>
        Friend Shared ReadOnly Property HeaderResources() As String
            Get
                Return ResourceManager.GetString("HeaderResources", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Administrador.
        '''</summary>
        Friend Shared ReadOnly Property HeaderTabAdministrator() As String
            Get
                Return ResourceManager.GetString("HeaderTabAdministrator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Candidato.
        '''</summary>
        Friend Shared ReadOnly Property HeaderTabCandidate() As String
            Get
                Return ResourceManager.GetString("HeaderTabCandidate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Coordinador.
        '''</summary>
        Friend Shared ReadOnly Property HeaderTabCoordinator() As String
            Get
                Return ResourceManager.GetString("HeaderTabCoordinator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Docente.
        '''</summary>
        Friend Shared ReadOnly Property HeaderTabProfesor() As String
            Get
                Return ResourceManager.GetString("HeaderTabProfesor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INICIO.
        '''</summary>
        Friend Shared ReadOnly Property HomeTitle() As String
            Get
                Return ResourceManager.GetString("HomeTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bienvenido al Sistema de Administración Docente CV-UDES.
        '''</summary>
        Friend Shared ReadOnly Property HomeTitle2() As String
            Get
                Return ResourceManager.GetString("HomeTitle2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cargando...  Por favor espere..
        '''</summary>
        Friend Shared ReadOnly Property LoadingPageSubtitle() As String
            Get
                Return ResourceManager.GetString("LoadingPageSubtitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Campus Virtual UDES - Sistema de Administración CV-UDES.
        '''</summary>
        Friend Shared ReadOnly Property LoadingPageTitle() As String
            Get
                Return ResourceManager.GetString("LoadingPageTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Procesando...  Por favor espere..
        '''</summary>
        Friend Shared ReadOnly Property ProcessingPageSubtitle() As String
            Get
                Return ResourceManager.GetString("ProcessingPageSubtitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Campus Virtual UDES - Sistema de Administración CV-UDES.
        '''</summary>
        Friend Shared ReadOnly Property ProcessingPageTitle() As String
            Get
                Return ResourceManager.GetString("ProcessingPageTitle", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
