'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Links
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.Links", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Activaciones programadas&apos;&gt;Activaciones programadas.
        '''</summary>
        Friend Shared ReadOnly Property lnkActivations() As String
            Get
                Return ResourceManager.GetString("lnkActivations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Nueva activación&apos;&gt;Nueva activación.
        '''</summary>
        Friend Shared ReadOnly Property lnkActivationsCreate() As String
            Get
                Return ResourceManager.GetString("lnkActivationsCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/ActivationsExecute.gif alt=&apos;Ejecutar proceso de activaciones&apos;&gt;Ejecutar proceso de activaciones.
        '''</summary>
        Friend Shared ReadOnly Property lnkActivationsExecute() As String
            Get
                Return ResourceManager.GetString("lnkActivationsExecute", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Cargar Informaci&amp;oacute;n Admin.EXCEL&apos;&gt;Cargar Informaci&amp;oacute;n Admin EXCEL..
        '''</summary>
        Friend Shared ReadOnly Property lnkAppLoadingInfoAdmin() As String
            Get
                Return ResourceManager.GetString("lnkAppLoadingInfoAdmin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Cargar Docentes EXCEL&apos;&gt;Cargar Docentes EXCEL.
        '''</summary>
        Friend Shared ReadOnly Property lnkAppLoadingProfessor() As String
            Get
                Return ResourceManager.GetString("lnkAppLoadingProfessor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Docente&apos;&gt;Docentes.
        '''</summary>
        Friend Shared ReadOnly Property lnkAppProfessor() As String
            Get
                Return ResourceManager.GetString("lnkAppProfessor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Reporets SNIES&apos;&gt;Reportes SNIES.
        '''</summary>
        Friend Shared ReadOnly Property lnkAppReports() As String
            Get
                Return ResourceManager.GetString("lnkAppReports", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Usuarios&apos;&gt;Usuarios.
        '''</summary>
        Friend Shared ReadOnly Property lnkAppUsers() As String
            Get
                Return ResourceManager.GetString("lnkAppUsers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Buscar Usuarios&apos;&gt;Buscar Usuarios.
        '''</summary>
        Friend Shared ReadOnly Property lnkAppUsers_Search() As String
            Get
                Return ResourceManager.GetString("lnkAppUsers_Search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Sesiones&apos;&gt;Sesiones.
        '''</summary>
        Friend Shared ReadOnly Property lnkAppUsers_Sessions() As String
            Get
                Return ResourceManager.GetString("lnkAppUsers_Sessions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Eventos de Error&apos;&gt;Eventos de Error.
        '''</summary>
        Friend Shared ReadOnly Property lnkApp_ErrorEvents() As String
            Get
                Return ResourceManager.GetString("lnkApp_ErrorEvents", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Eventos de Seguimiento&apos;&gt;Eventos de Seguimiento.
        '''</summary>
        Friend Shared ReadOnly Property lnkApp_TraceEvents() As String
            Get
                Return ResourceManager.GetString("lnkApp_TraceEvents", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Evaluaciones&apos;&gt;Evaluaciones.
        '''</summary>
        Friend Shared ReadOnly Property lnkAssessments() As String
            Get
                Return ResourceManager.GetString("lnkAssessments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Esquemas de evaluaciones&apos;&gt;Esquemas de evaluaciones.
        '''</summary>
        Friend Shared ReadOnly Property lnkAssessmentSchemes() As String
            Get
                Return ResourceManager.GetString("lnkAssessmentSchemes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Nuevo esquema&apos;&gt;Nuevo esquema.
        '''</summary>
        Friend Shared ReadOnly Property lnkAssessmentSchemesCreate() As String
            Get
                Return ResourceManager.GetString("lnkAssessmentSchemesCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Crear evaluación&apos;&gt;Crear evaluación.
        '''</summary>
        Friend Shared ReadOnly Property lnkAssessmentsCreate() As String
            Get
                Return ResourceManager.GetString("lnkAssessmentsCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Certificado de notas.
        '''</summary>
        Friend Shared ReadOnly Property lnkCertificationGrades() As String
            Get
                Return ResourceManager.GetString("lnkCertificationGrades", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Certificado de pagos.
        '''</summary>
        Friend Shared ReadOnly Property lnkCertificationPayments() As String
            Get
                Return ResourceManager.GetString("lnkCertificationPayments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Continuar.
        '''</summary>
        Friend Shared ReadOnly Property lnkContinue() As String
            Get
                Return ResourceManager.GetString("lnkContinue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Cursos y Capacitaciones&apos;&gt;Cursos y Capacitaciones.
        '''</summary>
        Friend Shared ReadOnly Property lnkCoursesAndTraining() As String
            Get
                Return ResourceManager.GetString("lnkCoursesAndTraining", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Documentos y Soportes&apos;&gt;Documentos y Soportes.
        '''</summary>
        Friend Shared ReadOnly Property lnkDocumentsAndSupports() As String
            Get
                Return ResourceManager.GetString("lnkDocumentsAndSupports", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Documentos anexos&apos;&gt;Documentos anexos.
        '''</summary>
        Friend Shared ReadOnly Property lnkEBookDocuments() As String
            Get
                Return ResourceManager.GetString("lnkEBookDocuments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Crear documento anexo&apos;&gt;Crear documento anexo.
        '''</summary>
        Friend Shared ReadOnly Property lnkEBookDocumentsCreate() As String
            Get
                Return ResourceManager.GetString("lnkEBookDocumentsCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Search.gif alt=&apos;Buscar documentos anexos&apos;&gt;Buscar documentos anexos.
        '''</summary>
        Friend Shared ReadOnly Property lnkEBookDocumentsSearch() As String
            Get
                Return ResourceManager.GetString("lnkEBookDocumentsSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Links temáticos&apos;&gt;Links temáticos.
        '''</summary>
        Friend Shared ReadOnly Property lnkEBookLinks() As String
            Get
                Return ResourceManager.GetString("lnkEBookLinks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Crear link temático&apos;&gt;Crear link temático.
        '''</summary>
        Friend Shared ReadOnly Property lnkEBookLinksCreate() As String
            Get
                Return ResourceManager.GetString("lnkEBookLinksCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Search.gif alt=&apos;Buscar links temáticos&apos;&gt;Buscar links temáticos.
        '''</summary>
        Friend Shared ReadOnly Property lnkEBookLinksSearch() As String
            Get
                Return ResourceManager.GetString("lnkEBookLinksSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Libros electrónicos&apos;&gt;Libros electrónicos.
        '''</summary>
        Friend Shared ReadOnly Property lnkEBooks() As String
            Get
                Return ResourceManager.GetString("lnkEBooks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Crear libro electrónico&apos;&gt;Crear libro electrónico.
        '''</summary>
        Friend Shared ReadOnly Property lnkEBooksCreate() As String
            Get
                Return ResourceManager.GetString("lnkEBooksCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Delete.gif alt=&apos;Borrar libro electrónico&apos;&gt;Borrar libro electrónico.
        '''</summary>
        Friend Shared ReadOnly Property lnkEBooksDelete() As String
            Get
                Return ResourceManager.GetString("lnkEBooksDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Edit.gif alt=&apos;Editar libro electrónico&apos;&gt;Editar libro electrónico.
        '''</summary>
        Friend Shared ReadOnly Property lnkEBooksEdit() As String
            Get
                Return ResourceManager.GetString("lnkEBooksEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/GridView.gif alt=&apos;Ver libros electrónicos&apos;&gt;Ver libros electrónicos.
        '''</summary>
        Friend Shared ReadOnly Property lnkEBooksGridView() As String
            Get
                Return ResourceManager.GetString("lnkEBooksGridView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Search.gif alt=&apos;Buscar libros electrónicos&apos;&gt;Buscar libros electrónicos.
        '''</summary>
        Friend Shared ReadOnly Property lnkEBooksSearch() As String
            Get
                Return ResourceManager.GetString("lnkEBooksSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Asignación de profesores&apos;&gt;Asignación de profesores.
        '''</summary>
        Friend Shared ReadOnly Property lnkEnrolledProfessors() As String
            Get
                Return ResourceManager.GetString("lnkEnrolledProfessors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Programas matriculados&apos;&gt;Programas matriculados.
        '''</summary>
        Friend Shared ReadOnly Property lnkEnrolledPrograms() As String
            Get
                Return ResourceManager.GetString("lnkEnrolledPrograms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Módulos matriculados&apos;&gt;Módulos matriculados.
        '''</summary>
        Friend Shared ReadOnly Property lnkEnrolledSubjects() As String
            Get
                Return ResourceManager.GetString("lnkEnrolledSubjects", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Asignación de tutores&apos;&gt;Asignación de tutores.
        '''</summary>
        Friend Shared ReadOnly Property lnkEnrolledTutors() As String
            Get
                Return ResourceManager.GetString("lnkEnrolledTutors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Matrículas&apos;&gt;Matrículas.
        '''</summary>
        Friend Shared ReadOnly Property lnkEnrollments() As String
            Get
                Return ResourceManager.GetString("lnkEnrollments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Experiencia Laboral&apos;&gt;Experiencia Laboral.
        '''</summary>
        Friend Shared ReadOnly Property lnkExperience() As String
            Get
                Return ResourceManager.GetString("lnkExperience", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Viajes al Exterior&apos;&gt;Viajes al Exterior.
        '''</summary>
        Friend Shared ReadOnly Property lnkForeingTravels() As String
            Get
                Return ResourceManager.GetString("lnkForeingTravels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Grupos&apos;&gt;Grupos.
        '''</summary>
        Friend Shared ReadOnly Property lnkGroups() As String
            Get
                Return ResourceManager.GetString("lnkGroups", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Programaciones de grupos&apos;&gt;Programaciones de grupos.
        '''</summary>
        Friend Shared ReadOnly Property lnkGroupSchedules() As String
            Get
                Return ResourceManager.GetString("lnkGroupSchedules", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Crear programación&apos;&gt;Crear programación.
        '''</summary>
        Friend Shared ReadOnly Property lnkGroupSchedulesCreate() As String
            Get
                Return ResourceManager.GetString("lnkGroupSchedulesCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/ActivationsExecute.gif alt=&apos;Matricular Grupo&apos;&gt;Matricular Grupo.
        '''</summary>
        Friend Shared ReadOnly Property lnkGroupSchedulesRegister() As String
            Get
                Return ResourceManager.GetString("lnkGroupSchedulesRegister", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Crear grupo&apos;&gt;Crear grupo.
        '''</summary>
        Friend Shared ReadOnly Property lnkGroupsCreate() As String
            Get
                Return ResourceManager.GetString("lnkGroupsCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Delete.gif alt=&apos;Borrar grupo&apos;&gt;Borrar grupo.
        '''</summary>
        Friend Shared ReadOnly Property lnkGroupsDelete() As String
            Get
                Return ResourceManager.GetString("lnkGroupsDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Edit.gif alt=&apos;Editar grupo&apos;&gt;Editar grupo.
        '''</summary>
        Friend Shared ReadOnly Property lnkGroupsEdit() As String
            Get
                Return ResourceManager.GetString("lnkGroupsEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/GridView.gif alt=&apos;Ver grupos&apos;&gt;Ver grupos.
        '''</summary>
        Friend Shared ReadOnly Property lnkGroupsGridView() As String
            Get
                Return ResourceManager.GetString("lnkGroupsGridView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Search.gif alt=&apos;Buscar grupos&apos;&gt;Buscar grupos.
        '''</summary>
        Friend Shared ReadOnly Property lnkGroupsSearch() As String
            Get
                Return ResourceManager.GetString("lnkGroupsSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Home.gif alt=&apos;Ir al inicio&apos;&gt;Ir al inicio.
        '''</summary>
        Friend Shared ReadOnly Property lnkHome() As String
            Get
                Return ResourceManager.GetString("lnkHome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Días de agenda de avance&apos;&gt;Días de agenda de avance.
        '''</summary>
        Friend Shared ReadOnly Property lnkLearningScheduleDays() As String
            Get
                Return ResourceManager.GetString("lnkLearningScheduleDays", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Crear día de agenda de avance&apos;&gt;Crear día de agenda de avance.
        '''</summary>
        Friend Shared ReadOnly Property lnkLearningScheduleDaysCreate() As String
            Get
                Return ResourceManager.GetString("lnkLearningScheduleDaysCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Agendas de avance&apos;&gt;Agendas de avance.
        '''</summary>
        Friend Shared ReadOnly Property lnkLearningSchedules() As String
            Get
                Return ResourceManager.GetString("lnkLearningSchedules", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Crear agenda de avance&apos;&gt;Crear agenda de avance.
        '''</summary>
        Friend Shared ReadOnly Property lnkLearningSchedulesCreate() As String
            Get
                Return ResourceManager.GetString("lnkLearningSchedulesCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Delete.gif alt=&apos;Borrar agenda de avance&apos;&gt;Borrar agenda de avance.
        '''</summary>
        Friend Shared ReadOnly Property lnkLearningSchedulesDelete() As String
            Get
                Return ResourceManager.GetString("lnkLearningSchedulesDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Edit.gif alt=&apos;Editar agenda de avance&apos;&gt;Editar agenda de avance.
        '''</summary>
        Friend Shared ReadOnly Property lnkLearningSchedulesEdit() As String
            Get
                Return ResourceManager.GetString("lnkLearningSchedulesEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/GridView.gif alt=&apos;Ver agendas de avance&apos;&gt;Ver agendas de avance.
        '''</summary>
        Friend Shared ReadOnly Property lnkLearningSchedulesGridView() As String
            Get
                Return ResourceManager.GetString("lnkLearningSchedulesGridView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Search.gif alt=&apos;Buscar agendas de avance&apos;&gt;Buscar agendas de avance.
        '''</summary>
        Friend Shared ReadOnly Property lnkLearningSchedulesSearch() As String
            Get
                Return ResourceManager.GetString("lnkLearningSchedulesSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¿Ha olvidado su contraseña?.
        '''</summary>
        Friend Shared ReadOnly Property lnkPasswordReset() As String
            Get
                Return ResourceManager.GetString("lnkPasswordReset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Datos Personales&apos;&gt;Datos Personales.
        '''</summary>
        Friend Shared ReadOnly Property lnkPersonalData() As String
            Get
                Return ResourceManager.GetString("lnkPersonalData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Profesores&apos;&gt;Profesores.
        '''</summary>
        Friend Shared ReadOnly Property lnkProfessors() As String
            Get
                Return ResourceManager.GetString("lnkProfessors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Crear profesor&apos;&gt;Crear profesor.
        '''</summary>
        Friend Shared ReadOnly Property lnkProfessorsCreate() As String
            Get
                Return ResourceManager.GetString("lnkProfessorsCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Delete.gif alt=&apos;Borrar profesor&apos;&gt;Borrar profesor.
        '''</summary>
        Friend Shared ReadOnly Property lnkProfessorsDelete() As String
            Get
                Return ResourceManager.GetString("lnkProfessorsDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Edit.gif alt=&apos;Editar profesor&apos;&gt;Editar profesor.
        '''</summary>
        Friend Shared ReadOnly Property lnkProfessorsEdit() As String
            Get
                Return ResourceManager.GetString("lnkProfessorsEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/GridView.gif alt=&apos;Ver profesores&apos;&gt;Ver profesores.
        '''</summary>
        Friend Shared ReadOnly Property lnkProfessorsGridView() As String
            Get
                Return ResourceManager.GetString("lnkProfessorsGridView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Search.gif alt=&apos;Buscar profesores&apos;&gt;Buscar profesores.
        '''</summary>
        Friend Shared ReadOnly Property lnkProfessorsSearch() As String
            Get
                Return ResourceManager.GetString("lnkProfessorsSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Módulos asignados&apos;&gt;Módulos asignados.
        '''</summary>
        Friend Shared ReadOnly Property lnkProfessorSubjects() As String
            Get
                Return ResourceManager.GetString("lnkProfessorSubjects", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Categorías&apos;&gt;Categorías.
        '''</summary>
        Friend Shared ReadOnly Property lnkProgramCategories() As String
            Get
                Return ResourceManager.GetString("lnkProgramCategories", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Crear categoría&apos;&gt;Crear categoría.
        '''</summary>
        Friend Shared ReadOnly Property lnkProgramCategoriesCreate() As String
            Get
                Return ResourceManager.GetString("lnkProgramCategoriesCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Programas&apos;&gt;Programas.
        '''</summary>
        Friend Shared ReadOnly Property lnkPrograms() As String
            Get
                Return ResourceManager.GetString("lnkPrograms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Crear programa&apos;&gt;Crear programa.
        '''</summary>
        Friend Shared ReadOnly Property lnkProgramsCreate() As String
            Get
                Return ResourceManager.GetString("lnkProgramsCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Delete.gif alt=&apos;Borrar programa&apos;&gt;Borrar programa.
        '''</summary>
        Friend Shared ReadOnly Property lnkProgramsDelete() As String
            Get
                Return ResourceManager.GetString("lnkProgramsDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Edit.gif alt=&apos;Editar programa&apos;&gt;Editar programa.
        '''</summary>
        Friend Shared ReadOnly Property lnkProgramsEdit() As String
            Get
                Return ResourceManager.GetString("lnkProgramsEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/GridView.gif alt=&apos;Ver programas&apos;&gt;Ver programas.
        '''</summary>
        Friend Shared ReadOnly Property lnkProgramsGridView() As String
            Get
                Return ResourceManager.GetString("lnkProgramsGridView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Search.gif alt=&apos;Buscar programas&apos;&gt;Buscar programas.
        '''</summary>
        Friend Shared ReadOnly Property lnkProgramsSearch() As String
            Get
                Return ResourceManager.GetString("lnkProgramsSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Publicaciones y Otros&apos;&gt;Publicaciones y Otros.
        '''</summary>
        Friend Shared ReadOnly Property lnkPublicationsAndOthers() As String
            Get
                Return ResourceManager.GetString("lnkPublicationsAndOthers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Group_gear.png alt=&apos;Matricular Grupo&apos;&gt;Matricular Grupo.
        '''</summary>
        Friend Shared ReadOnly Property lnkRegister() As String
            Get
                Return ResourceManager.GetString("lnkRegister", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Inscripciones&apos;&gt;Inscripciones.
        '''</summary>
        Friend Shared ReadOnly Property lnkRegistrations() As String
            Get
                Return ResourceManager.GetString("lnkRegistrations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Nueva inscripción&apos;&gt;Nueva inscripción.
        '''</summary>
        Friend Shared ReadOnly Property lnkRegistrationsCreate() As String
            Get
                Return ResourceManager.GetString("lnkRegistrationsCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Search.gif alt=&apos;Buscar inscripciones&apos;&gt;Buscar inscripciones.
        '''</summary>
        Friend Shared ReadOnly Property lnkRegistrationsSearch() As String
            Get
                Return ResourceManager.GetString("lnkRegistrationsSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;a href=&quot;/Public/Register/PreRegister.aspx&quot; id=&quot;Registrece&quot; &gt;Registrece Aquí&lt;/a&gt;.
        '''</summary>
        Friend Shared ReadOnly Property lnkRegistreceAqui() As String
            Get
                Return ResourceManager.GetString("lnkRegistreceAqui", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Recursos Locales&apos;&gt;Archivos de Recursos Locales.
        '''</summary>
        Friend Shared ReadOnly Property lnkResourceFilesLocal() As String
            Get
                Return ResourceManager.GetString("lnkResourceFilesLocal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Recursos Compartidos&apos;&gt;Archivos de Recursos Compartidos.
        '''</summary>
        Friend Shared ReadOnly Property lnkResourceFilesShared() As String
            Get
                Return ResourceManager.GetString("lnkResourceFilesShared", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Iniciar Sesión.
        '''</summary>
        Friend Shared ReadOnly Property lnkSignIn() As String
            Get
                Return ResourceManager.GetString("lnkSignIn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cerrar Sesión.
        '''</summary>
        Friend Shared ReadOnly Property lnkSignOut() As String
            Get
                Return ResourceManager.GetString("lnkSignOut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Estudiantes&apos;&gt;Estudiantes.
        '''</summary>
        Friend Shared ReadOnly Property lnkStudents() As String
            Get
                Return ResourceManager.GetString("lnkStudents", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Crear estudiante&apos;&gt;Crear estudiante.
        '''</summary>
        Friend Shared ReadOnly Property lnkStudentsCreate() As String
            Get
                Return ResourceManager.GetString("lnkStudentsCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Delete.gif alt=&apos;Borrar estudiante&apos;&gt;Borrar estudiante.
        '''</summary>
        Friend Shared ReadOnly Property lnkStudentsDelete() As String
            Get
                Return ResourceManager.GetString("lnkStudentsDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Edit.gif alt=&apos;Editar estudiante&apos;&gt;Editar estudiante.
        '''</summary>
        Friend Shared ReadOnly Property lnkStudentsEdit() As String
            Get
                Return ResourceManager.GetString("lnkStudentsEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/GridView.gif alt=&apos;Ver estudiantes&apos;&gt;Ver estudiantes.
        '''</summary>
        Friend Shared ReadOnly Property lnkStudentsGridView() As String
            Get
                Return ResourceManager.GetString("lnkStudentsGridView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Search.gif alt=&apos;Buscar estudiantes&apos;&gt;Buscar estudiantes.
        '''</summary>
        Friend Shared ReadOnly Property lnkStudentsSearch() As String
            Get
                Return ResourceManager.GetString("lnkStudentsSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Detalles de la órden&apos;&gt;Detalles de la órden.
        '''</summary>
        Friend Shared ReadOnly Property lnkStudentSubjectOrderItems() As String
            Get
                Return ResourceManager.GetString("lnkStudentSubjectOrderItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Agregar módulos&apos;&gt;Agregar módulos.
        '''</summary>
        Friend Shared ReadOnly Property lnkStudentSubjectOrderItemsCreate() As String
            Get
                Return ResourceManager.GetString("lnkStudentSubjectOrderItemsCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Ordenes de compra&apos;&gt;Ordenes de compra.
        '''</summary>
        Friend Shared ReadOnly Property lnkStudentSubjectOrders() As String
            Get
                Return ResourceManager.GetString("lnkStudentSubjectOrders", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Crear órden de compra&apos;&gt;Crear órden de compra.
        '''</summary>
        Friend Shared ReadOnly Property lnkStudentSubjectOrdersCreate() As String
            Get
                Return ResourceManager.GetString("lnkStudentSubjectOrdersCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Delete.gif alt=&apos;Borrar profesor&apos;&gt;Borrar órden de compra.
        '''</summary>
        Friend Shared ReadOnly Property lnkStudentSubjectOrdersDelete() As String
            Get
                Return ResourceManager.GetString("lnkStudentSubjectOrdersDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Edit.gif alt=&apos;Editar profesor&apos;&gt;Editar órden de compra.
        '''</summary>
        Friend Shared ReadOnly Property lnkStudentSubjectOrdersEdit() As String
            Get
                Return ResourceManager.GetString("lnkStudentSubjectOrdersEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/GridView.gif alt=&apos;Ver profesores&apos;&gt;Ver ordenes de compra.
        '''</summary>
        Friend Shared ReadOnly Property lnkStudentSubjectOrdersGridView() As String
            Get
                Return ResourceManager.GetString("lnkStudentSubjectOrdersGridView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Search.gif alt=&apos;Buscar ordenes&apos;&gt;Buscar ordenes.
        '''</summary>
        Friend Shared ReadOnly Property lnkStudentSubjectOrdersSearch() As String
            Get
                Return ResourceManager.GetString("lnkStudentSubjectOrdersSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Actualizar ahora.
        '''</summary>
        Friend Shared ReadOnly Property lnkStudentSubjectOrdersUpdater() As String
            Get
                Return ResourceManager.GetString("lnkStudentSubjectOrdersUpdater", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Módulos&apos;&gt;Módulos.
        '''</summary>
        Friend Shared ReadOnly Property lnkStudentSubjects() As String
            Get
                Return ResourceManager.GetString("lnkStudentSubjects", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Planes de estudio&apos;&gt;Planes de estudio.
        '''</summary>
        Friend Shared ReadOnly Property lnkStudentSyllabuses() As String
            Get
                Return ResourceManager.GetString("lnkStudentSyllabuses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Asignar plan de estudio&apos;&gt;Asignar plan de estudio.
        '''</summary>
        Friend Shared ReadOnly Property lnkStudentSyllabusesCreate() As String
            Get
                Return ResourceManager.GetString("lnkStudentSyllabusesCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Asignar libro electrónico&apos;&gt;Asignar libro electrónico.
        '''</summary>
        Friend Shared ReadOnly Property lnkSubjectEBooksCreate() As String
            Get
                Return ResourceManager.GetString("lnkSubjectEBooksCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Asignar módulo&apos;&gt;Asignar módulo.
        '''</summary>
        Friend Shared ReadOnly Property lnkSubjectProfessorsCreate() As String
            Get
                Return ResourceManager.GetString("lnkSubjectProfessorsCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Módulos&apos;&gt;Módulos.
        '''</summary>
        Friend Shared ReadOnly Property lnkSubjects() As String
            Get
                Return ResourceManager.GetString("lnkSubjects", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Crear módulo&apos;&gt;Crear módulo.
        '''</summary>
        Friend Shared ReadOnly Property lnkSubjectsCreate() As String
            Get
                Return ResourceManager.GetString("lnkSubjectsCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create_Off.gif alt=&apos;Crear módulo&apos;&gt;Crear módulo.
        '''</summary>
        Friend Shared ReadOnly Property lnkSubjectsCreate_Off() As String
            Get
                Return ResourceManager.GetString("lnkSubjectsCreate_Off", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Delete.gif alt=&apos;Borrar módulo&apos;&gt;Borrar módulo.
        '''</summary>
        Friend Shared ReadOnly Property lnkSubjectsDelete() As String
            Get
                Return ResourceManager.GetString("lnkSubjectsDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Delete_Off.gif alt=&apos;Borrar módulo&apos;&gt;Borrar módulo.
        '''</summary>
        Friend Shared ReadOnly Property lnkSubjectsDelete_Off() As String
            Get
                Return ResourceManager.GetString("lnkSubjectsDelete_Off", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Edit.gif alt=&apos;Editar módulo&apos;&gt;Editar módulo.
        '''</summary>
        Friend Shared ReadOnly Property lnkSubjectsEdit() As String
            Get
                Return ResourceManager.GetString("lnkSubjectsEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Edit_Off.gif alt=&apos;Editar módulo&apos;&gt;Editar módulo.
        '''</summary>
        Friend Shared ReadOnly Property lnkSubjectsEdit_Off() As String
            Get
                Return ResourceManager.GetString("lnkSubjectsEdit_Off", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/GridView.gif alt=&apos;Ver módulos&apos;&gt;Ver módulos.
        '''</summary>
        Friend Shared ReadOnly Property lnkSubjectsGridView() As String
            Get
                Return ResourceManager.GetString("lnkSubjectsGridView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Search.gif alt=&apos;Buscar módulos&apos;&gt;Buscar módulos.
        '''</summary>
        Friend Shared ReadOnly Property lnkSubjectsSearch() As String
            Get
                Return ResourceManager.GetString("lnkSubjectsSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Asignar módulo&apos;&gt;Asignar módulo.
        '''</summary>
        Friend Shared ReadOnly Property lnkSubjectTutorsCreate() As String
            Get
                Return ResourceManager.GetString("lnkSubjectTutorsCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Planes de estudio&apos;&gt;Planes de estudio.
        '''</summary>
        Friend Shared ReadOnly Property lnkSyllabuses() As String
            Get
                Return ResourceManager.GetString("lnkSyllabuses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Crear plan de estudio&apos;&gt;Crear plan de estudio.
        '''</summary>
        Friend Shared ReadOnly Property lnkSyllabusesCreate() As String
            Get
                Return ResourceManager.GetString("lnkSyllabusesCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Delete.gif alt=&apos;Borrar plan de estudio&apos;&gt;Borrar plan de estudio.
        '''</summary>
        Friend Shared ReadOnly Property lnkSyllabusesDelete() As String
            Get
                Return ResourceManager.GetString("lnkSyllabusesDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Edit.gif alt=&apos;Editar plan de estudio&apos;&gt;Editar plan de estudio.
        '''</summary>
        Friend Shared ReadOnly Property lnkSyllabusesEdit() As String
            Get
                Return ResourceManager.GetString("lnkSyllabusesEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/GridView.gif alt=&apos;Ver planes de estudio&apos;&gt;Ver planes de estudio.
        '''</summary>
        Friend Shared ReadOnly Property lnkSyllabusesGridView() As String
            Get
                Return ResourceManager.GetString("lnkSyllabusesGridView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Search.gif alt=&apos;Buscar planes de estudio&apos;&gt;Buscar planes de estudio.
        '''</summary>
        Friend Shared ReadOnly Property lnkSyllabusesSearch() As String
            Get
                Return ResourceManager.GetString("lnkSyllabusesSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Niveles&apos;&gt;Niveles.
        '''</summary>
        Friend Shared ReadOnly Property lnkSyllabusLevels() As String
            Get
                Return ResourceManager.GetString("lnkSyllabusLevels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Crear nivel&apos;&gt;Crear nivel.
        '''</summary>
        Friend Shared ReadOnly Property lnkSyllabusLevelsCreate() As String
            Get
                Return ResourceManager.GetString("lnkSyllabusLevelsCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Módulos&apos;&gt;Módulos.
        '''</summary>
        Friend Shared ReadOnly Property lnkSyllabusSubjects() As String
            Get
                Return ResourceManager.GetString("lnkSyllabusSubjects", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Asignar módulo&apos;&gt;Asignar módulo.
        '''</summary>
        Friend Shared ReadOnly Property lnkSyllabusSubjectsCreate() As String
            Get
                Return ResourceManager.GetString("lnkSyllabusSubjectsCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Crear Traspaso de Estudiante&apos;&gt;Crear Traspaso de Estudiante   .
        '''</summary>
        Friend Shared ReadOnly Property lnkTransfersStudentsCreate() As String
            Get
                Return ResourceManager.GetString("lnkTransfersStudentsCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Tutores&apos;&gt;Tutores.
        '''</summary>
        Friend Shared ReadOnly Property lnkTutors() As String
            Get
                Return ResourceManager.GetString("lnkTutors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Crear tutor&apos;&gt;Crear tutor.
        '''</summary>
        Friend Shared ReadOnly Property lnkTutorsCreate() As String
            Get
                Return ResourceManager.GetString("lnkTutorsCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Delete.gif alt=&apos;Borrar tutor&apos;&gt;Borrar tutor.
        '''</summary>
        Friend Shared ReadOnly Property lnkTutorsDelete() As String
            Get
                Return ResourceManager.GetString("lnkTutorsDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Edit.gif alt=&apos;Editar tutor&apos;&gt;Editar tutor.
        '''</summary>
        Friend Shared ReadOnly Property lnkTutorsEdit() As String
            Get
                Return ResourceManager.GetString("lnkTutorsEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/GridView.gif alt=&apos;Ver tutores&apos;&gt;Ver tutores.
        '''</summary>
        Friend Shared ReadOnly Property lnkTutorsGridView() As String
            Get
                Return ResourceManager.GetString("lnkTutorsGridView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Search.gif alt=&apos;Buscar tutores&apos;&gt;Buscar tutores.
        '''</summary>
        Friend Shared ReadOnly Property lnkTutorsSearch() As String
            Get
                Return ResourceManager.GetString("lnkTutorsSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Módulos asignados&apos;&gt;Módulos asignados.
        '''</summary>
        Friend Shared ReadOnly Property lnkTutorSubjects() As String
            Get
                Return ResourceManager.GetString("lnkTutorSubjects", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Grupos&apos;&gt;Grupos.
        '''</summary>
        Friend Shared ReadOnly Property lnkUserGroups() As String
            Get
                Return ResourceManager.GetString("lnkUserGroups", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Asignar grupo&apos;&gt;Asignar grupo.
        '''</summary>
        Friend Shared ReadOnly Property lnkUserGroupsCreate() As String
            Get
                Return ResourceManager.GetString("lnkUserGroupsCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Asignar rol&apos;&gt;Asignar rol.
        '''</summary>
        Friend Shared ReadOnly Property lnkUserRolesCreate() As String
            Get
                Return ResourceManager.GetString("lnkUserRolesCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Usuarios&apos;&gt;Usuarios.
        '''</summary>
        Friend Shared ReadOnly Property lnkUsers() As String
            Get
                Return ResourceManager.GetString("lnkUsers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Create.gif alt=&apos;Crear usuario&apos;&gt;Crear usuario.
        '''</summary>
        Friend Shared ReadOnly Property lnkUsersCreate() As String
            Get
                Return ResourceManager.GetString("lnkUsersCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Delete.gif alt=&apos;Borrar usuario&apos;&gt;Borrar usuario.
        '''</summary>
        Friend Shared ReadOnly Property lnkUsersDelete() As String
            Get
                Return ResourceManager.GetString("lnkUsersDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Edit.gif alt=&apos;Editar usuario&apos;&gt;Editar usuario.
        '''</summary>
        Friend Shared ReadOnly Property lnkUsersEdit() As String
            Get
                Return ResourceManager.GetString("lnkUsersEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Sesiones en el aula&apos;&gt;Sesiones en el aula.
        '''</summary>
        Friend Shared ReadOnly Property lnkUserSessions() As String
            Get
                Return ResourceManager.GetString("lnkUserSessions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/GridView.gif alt=&apos;Ver usuarios&apos;&gt;Ver usuarios.
        '''</summary>
        Friend Shared ReadOnly Property lnkUsersGridView() As String
            Get
                Return ResourceManager.GetString("lnkUsersGridView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Roles&apos;&gt;Roles.
        '''</summary>
        Friend Shared ReadOnly Property lnkUsersRoles() As String
            Get
                Return ResourceManager.GetString("lnkUsersRoles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Search.gif alt=&apos;Buscar usuarios&apos;&gt;Buscar usuarios.
        '''</summary>
        Friend Shared ReadOnly Property lnkUsersSearch() As String
            Get
                Return ResourceManager.GetString("lnkUsersSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Sesiones&apos;&gt;Sesiones.
        '''</summary>
        Friend Shared ReadOnly Property lnkUsersSessions() As String
            Get
                Return ResourceManager.GetString("lnkUsersSessions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Contenidos Web&apos;&gt;Contenidos Web.
        '''</summary>
        Friend Shared ReadOnly Property lnkUsersWebContents() As String
            Get
                Return ResourceManager.GetString("lnkUsersWebContents", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Documentos Web&apos;&gt;Documentos Web.
        '''</summary>
        Friend Shared ReadOnly Property lnkUsersWebDocuments() As String
            Get
                Return ResourceManager.GetString("lnkUsersWebDocuments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ver perfil.
        '''</summary>
        Friend Shared ReadOnly Property lnkViewProfile() As String
            Get
                Return ResourceManager.GetString("lnkViewProfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;img src=/_Resources/Icons/Folder.gif alt=&apos;Formación Profesional&apos;&gt;Formación Profesional Académica.
        '''</summary>
        Friend Shared ReadOnly Property lnkVocationalTraining() As String
            Get
                Return ResourceManager.GetString("lnkVocationalTraining", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
