'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Tags
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.Tags", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Información Académica.
        '''</summary>
        Friend Shared ReadOnly Property tagAcademicInformation() As String
            Get
                Return ResourceManager.GetString("tagAcademicInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Información Complementaria.
        '''</summary>
        Friend Shared ReadOnly Property tagAdditionalInformation() As String
            Get
                Return ResourceManager.GetString("tagAdditionalInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opciones del Administrador.
        '''</summary>
        Friend Shared ReadOnly Property tagAdministratorOptions() As String
            Get
                Return ResourceManager.GetString("tagAdministratorOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Código de Área.
        '''</summary>
        Friend Shared ReadOnly Property tagAreaPhoneNumber() As String
            Get
                Return ResourceManager.GetString("tagAreaPhoneNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fecha de Nacimiento:.
        '''</summary>
        Friend Shared ReadOnly Property tagBirthDate() As String
            Get
                Return ResourceManager.GetString("tagBirthDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opciones del Candidato.
        '''</summary>
        Friend Shared ReadOnly Property tagCandidateOptions() As String
            Get
                Return ResourceManager.GetString("tagCandidateOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Número Teléfono Móvil.
        '''</summary>
        Friend Shared ReadOnly Property tagCellPhoneNumber() As String
            Get
                Return ResourceManager.GetString("tagCellPhoneNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Número Teléfono Móvil Alternativo.
        '''</summary>
        Friend Shared ReadOnly Property tagCellPhoneNumberAlternative() As String
            Get
                Return ResourceManager.GetString("tagCellPhoneNumberAlternative", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opciones Comunes.
        '''</summary>
        Friend Shared ReadOnly Property tagCommonOptions() As String
            Get
                Return ResourceManager.GetString("tagCommonOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El uso que Usted haga de este formulario de inscripción o de las todas las páginas
        '''                                        del CV-UDES se regirá por los términos y declaraciones siguientes, denominados colectivamente
        '''                                        los &quot;Acuerdos&quot;:&lt;br&gt;
        '''                                        &lt;br&gt;
        '''                                        &lt;a target=&quot;_blank&quot; href=&quot;http://www.cvudes.edu.co/Terminos.aspx&quot;&gt;Términos de Uso&lt;/a&gt;&lt;br&gt;
        '''                                        &lt;a target=&quot;_blan [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property tagConditions() As String
            Get
                Return ResourceManager.GetString("tagConditions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Se ha enviado un Correo Electr&amp;oacute;nico de Verificaci&amp;oacute;n de su registro. Por favor revise su Correo Electr&amp;oacute;nico para continuar el proceso de Inscripci&amp;oacute;n..
        '''</summary>
        Friend Shared ReadOnly Property tagConfirmation() As String
            Get
                Return ResourceManager.GetString("tagConfirmation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opciones del Coordinador.
        '''</summary>
        Friend Shared ReadOnly Property tagCoordinatorOptions() As String
            Get
                Return ResourceManager.GetString("tagCoordinatorOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gracias por considerar a nuestra Institución como la mejor alternativa para ejercer su desarrollo profesional; Por favor suministre la información que a continuación le solicitamos. Toda la información debe ser veraz; ésta será verificada por la Dirección del Departamento de Recurso Humano - UDES..
        '''</summary>
        Friend Shared ReadOnly Property tagDescription() As String
            Get
                Return ResourceManager.GetString("tagDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Por favor ingrese su información personal. &lt;br /&gt;Todos estos datos son obligatorios..
        '''</summary>
        Friend Shared ReadOnly Property tagDescriptionPreRegister() As String
            Get
                Return ResourceManager.GetString("tagDescriptionPreRegister", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Por favor ingrese su información personal. Todos estos datos son obligatorios..
        '''</summary>
        Friend Shared ReadOnly Property tagDescriptionSeccion1() As String
            Get
                Return ResourceManager.GetString("tagDescriptionSeccion1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Por favor ingrese la información que nos permitirá ponernos en contacto con Usted. Le rogamos que no use abreviaturas. Es importante que constate su dirección de correo electrónico ya que este será el medio primordial por el cual nos comunicaremos con Usted..
        '''</summary>
        Friend Shared ReadOnly Property tagDescriptionSeccion2() As String
            Get
                Return ResourceManager.GetString("tagDescriptionSeccion2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleccione el plan de estudios al cual desea aplicar. Los reglamentos del CV-UDES no permiten que un aspirante aplique para más de un Programa Académico simultáneamente. Por favor decida cual de nuestros programas es el más apropiado para Usted, antes de enviar la solicitud de inscripción..
        '''</summary>
        Friend Shared ReadOnly Property tagDescriptionSeccion3() As String
            Get
                Return ResourceManager.GetString("tagDescriptionSeccion3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Para diligenciar este formulario es necesario que Usted acepte los Términos de Uso y la Política de Privacidad y Seguridad de este sitio Web..
        '''</summary>
        Friend Shared ReadOnly Property tagDescriptionSeccion4() As String
            Get
                Return ResourceManager.GetString("tagDescriptionSeccion4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Por favor, Indique los codigos de Corretaje y Lider.
        '''</summary>
        Friend Shared ReadOnly Property tagDescriptionSeccion5() As String
            Get
                Return ResourceManager.GetString("tagDescriptionSeccion5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Correo Electr&amp;oacute;nico:.
        '''</summary>
        Friend Shared ReadOnly Property tagEmail() As String
            Get
                Return ResourceManager.GetString("tagEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirmar Correo Electrónico:.
        '''</summary>
        Friend Shared ReadOnly Property tagEmail2() As String
            Get
                Return ResourceManager.GetString("tagEmail2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fecha de Expedici&amp;oacute;n:.
        '''</summary>
        Friend Shared ReadOnly Property tagExpeditionDate() As String
            Get
                Return ResourceManager.GetString("tagExpeditionDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Primer Nombre:.
        '''</summary>
        Friend Shared ReadOnly Property tagFirstName() As String
            Get
                Return ResourceManager.GetString("tagFirstName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Primer Apellido:.
        '''</summary>
        Friend Shared ReadOnly Property tagFirstSurname() As String
            Get
                Return ResourceManager.GetString("tagFirstSurname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Género:.
        '''</summary>
        Friend Shared ReadOnly Property tagGender() As String
            Get
                Return ResourceManager.GetString("tagGender", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ayuda.
        '''</summary>
        Friend Shared ReadOnly Property tagHelp() As String
            Get
                Return ResourceManager.GetString("tagHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Número Documento de Identidad:.
        '''</summary>
        Friend Shared ReadOnly Property tagIdentification() As String
            Get
                Return ResourceManager.GetString("tagIdentification", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tipo Documento de Identidad:.
        '''</summary>
        Friend Shared ReadOnly Property tagIdentificationDocumentType() As String
            Get
                Return ResourceManager.GetString("tagIdentificationDocumentType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ciudad:.
        '''</summary>
        Friend Shared ReadOnly Property tagIdentificationIssuedLocation() As String
            Get
                Return ResourceManager.GetString("tagIdentificationIssuedLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pais:.
        '''</summary>
        Friend Shared ReadOnly Property tagIdentificationIssuedLocationCountry() As String
            Get
                Return ResourceManager.GetString("tagIdentificationIssuedLocationCountry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Departamento:.
        '''</summary>
        Friend Shared ReadOnly Property tagIdentificationIssuedLocationRegion() As String
            Get
                Return ResourceManager.GetString("tagIdentificationIssuedLocationRegion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inicie Sesión.
        '''</summary>
        Friend Shared ReadOnly Property tagInicioSesion() As String
            Get
                Return ResourceManager.GetString("tagInicioSesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Código Lider.
        '''</summary>
        Friend Shared ReadOnly Property tagLeaderCode() As String
            Get
                Return ResourceManager.GetString("tagLeaderCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estado Civíl:.
        '''</summary>
        Friend Shared ReadOnly Property tagMaritalStatusType() As String
            Get
                Return ResourceManager.GetString("tagMaritalStatusType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Segundo Nombre:.
        '''</summary>
        Friend Shared ReadOnly Property tagMiddleName() As String
            Get
                Return ResourceManager.GetString("tagMiddleName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Segundo Apellido:.
        '''</summary>
        Friend Shared ReadOnly Property tagMiddleSurname() As String
            Get
                Return ResourceManager.GetString("tagMiddleSurname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nombre de Usuario o Nick:.
        '''</summary>
        Friend Shared ReadOnly Property tagNickUserName() As String
            Get
                Return ResourceManager.GetString("tagNickUserName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Si Usted no es colombiano, y/o su título profesional fue obtenido en un país extranjero,
        '''                                                                            aquel deberá ser convalidado en Colombia. Si desea obtener más información acerca
        '''                                                                            de cómo convalidar su título profesional, por favor escríbanos a la &lt;a title=&quot;admisiones@campusvirtualudes.edu.co&quot; href=&quot;mailto:admisiones@campusvirtualudes.edu.co&quot;&gt;Dirección de Admisión  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property tagNoteProgram() As String
            Get
                Return ResourceManager.GetString("tagNoteProgram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Su Incripción ha sido Activada Correctamente. Se ha enviado un correo electr&amp;oacute;nico confirmando la activación de la cuenta. &lt;br /&gt;&lt;br /&gt;Por favor consultar el mensaje y seguir las instruccones para continuar con el proceso de registro, si desea puede aceder al sistema de contratación docente, presionando el botón &lt;Strong&gt;Iniciar Sesión&lt;/Strong&gt;..
        '''</summary>
        Friend Shared ReadOnly Property tagNotification() As String
            Get
                Return ResourceManager.GetString("tagNotification", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ocupación:.
        '''</summary>
        Friend Shared ReadOnly Property tagOccupation() As String
            Get
                Return ResourceManager.GetString("tagOccupation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Digite una contraseña:.
        '''</summary>
        Friend Shared ReadOnly Property tagPassword() As String
            Get
                Return ResourceManager.GetString("tagPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Repita la contraseña:.
        '''</summary>
        Friend Shared ReadOnly Property tagPassword2() As String
            Get
                Return ResourceManager.GetString("tagPassword2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Información Personal.
        '''</summary>
        Friend Shared ReadOnly Property tagPersonalInformation() As String
            Get
                Return ResourceManager.GetString("tagPersonalInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Número Teléfono Fijo.
        '''</summary>
        Friend Shared ReadOnly Property tagPhoneNumber() As String
            Get
                Return ResourceManager.GetString("tagPhoneNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ciudad de Nacimiento:.
        '''</summary>
        Friend Shared ReadOnly Property tagPlaceBirth() As String
            Get
                Return ResourceManager.GetString("tagPlaceBirth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pais de Nacimiento:.
        '''</summary>
        Friend Shared ReadOnly Property tagPlaceBirthCountry() As String
            Get
                Return ResourceManager.GetString("tagPlaceBirthCountry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Departamento Nacimiento:.
        '''</summary>
        Friend Shared ReadOnly Property tagPlaceBirthRegion() As String
            Get
                Return ResourceManager.GetString("tagPlaceBirthRegion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Profesión:.
        '''</summary>
        Friend Shared ReadOnly Property tagProfession() As String
            Get
                Return ResourceManager.GetString("tagProfession", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opciones del Docente.
        '''</summary>
        Friend Shared ReadOnly Property tagProfessorOptions() As String
            Get
                Return ResourceManager.GetString("tagProfessorOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Programa Académico:.
        '''</summary>
        Friend Shared ReadOnly Property tagProgram() As String
            Get
                Return ResourceManager.GetString("tagProgram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reportes SNIES.
        '''</summary>
        Friend Shared ReadOnly Property tagReports() As String
            Get
                Return ResourceManager.GetString("tagReports", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dirección:.
        '''</summary>
        Friend Shared ReadOnly Property tagResidenceAddress() As String
            Get
                Return ResourceManager.GetString("tagResidenceAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ciudad:.
        '''</summary>
        Friend Shared ReadOnly Property tagResidencePlace() As String
            Get
                Return ResourceManager.GetString("tagResidencePlace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pais:.
        '''</summary>
        Friend Shared ReadOnly Property tagResidencePlaceCountry() As String
            Get
                Return ResourceManager.GetString("tagResidencePlaceCountry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Departamento:.
        '''</summary>
        Friend Shared ReadOnly Property tagResidencePlaceRegion() As String
            Get
                Return ResourceManager.GetString("tagResidencePlaceRegion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buscar ....
        '''</summary>
        Friend Shared ReadOnly Property tagSearch() As String
            Get
                Return ResourceManager.GetString("tagSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inicie Sesión.
        '''</summary>
        Friend Shared ReadOnly Property tagSingIn() As String
            Get
                Return ResourceManager.GetString("tagSingIn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirmación del Registro.
        '''</summary>
        Friend Shared ReadOnly Property tagTittleConfirmation() As String
            Get
                Return ResourceManager.GetString("tagTittleConfirmation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Notificación Inscripción.
        '''</summary>
        Friend Shared ReadOnly Property tagTittleNotification() As String
            Get
                Return ResourceManager.GetString("tagTittleNotification", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Formulario de Registro - Proceso de Contratación Docente.
        '''</summary>
        Friend Shared ReadOnly Property tagTittlePage() As String
            Get
                Return ResourceManager.GetString("tagTittlePage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Información Personal.
        '''</summary>
        Friend Shared ReadOnly Property tagTittleSeccion1() As String
            Get
                Return ResourceManager.GetString("tagTittleSeccion1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Información de Contacto.
        '''</summary>
        Friend Shared ReadOnly Property tagTittleSeccion2() As String
            Get
                Return ResourceManager.GetString("tagTittleSeccion2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Programa Académico.
        '''</summary>
        Friend Shared ReadOnly Property tagTittleSeccion3() As String
            Get
                Return ResourceManager.GetString("tagTittleSeccion3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comprobación y Aceptación de los Términos.
        '''</summary>
        Friend Shared ReadOnly Property tagTittleSeccion4() As String
            Get
                Return ResourceManager.GetString("tagTittleSeccion4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Infomación de Mercadeo.
        '''</summary>
        Friend Shared ReadOnly Property tagTittleSeccion5() As String
            Get
                Return ResourceManager.GetString("tagTittleSeccion5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usuario:.
        '''</summary>
        Friend Shared ReadOnly Property tagUser() As String
            Get
                Return ResourceManager.GetString("tagUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Información del Usuario.
        '''</summary>
        Friend Shared ReadOnly Property tagUserInformation() As String
            Get
                Return ResourceManager.GetString("tagUserInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nombre de Usuario.
        '''</summary>
        Friend Shared ReadOnly Property tagUserName() As String
            Get
                Return ResourceManager.GetString("tagUserName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contraseña.
        '''</summary>
        Friend Shared ReadOnly Property tagUserPassword() As String
            Get
                Return ResourceManager.GetString("tagUserPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opciones de Usuarios.
        '''</summary>
        Friend Shared ReadOnly Property tagUsersOptions() As String
            Get
                Return ResourceManager.GetString("tagUsersOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ver Información de ....
        '''</summary>
        Friend Shared ReadOnly Property tagViewInformation() As String
            Get
                Return ResourceManager.GetString("tagViewInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Código Corretaje.
        '''</summary>
        Friend Shared ReadOnly Property tagWanderingsCode() As String
            Get
                Return ResourceManager.GetString("tagWanderingsCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sitio Web.
        '''</summary>
        Friend Shared ReadOnly Property tagWebSite() As String
            Get
                Return ResourceManager.GetString("tagWebSite", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
